name: push shutter page to darts-portal static webapp
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  workflow_dispatch:
  check_run:
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - 'darts-portal/**'
      - .github/workflows/darts-portal.yaml

  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'darts-portal/**'
      - .github/workflows/darts-portal.yaml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      shutter_page_folder: "darts-portal"
    secrets:
      WEBAPP_TOKEN: ${{ secrets.DARTS_PORTAL_PROD }}
