name: push shutter page to sptribs-dss-update-case-web static webapp
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  workflow_dispatch:
  check_run:
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - 'sptribs-dss-update-case-web/**'
      - .github/workflows/sptribs-dss-update-case-web.yaml

  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'sptribs-dss-update-case-web/**'
      - .github/workflows/sptribs-dss-update-case-web.yaml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      shutter_page_folder: "sptribs-dss-update-case-web" # App source code path relative to repository root. Enter "default" for default pages.
    secrets:
      WEBAPP_TOKEN: ${{ secrets.SPTRIBS_DSS_UPDATE_CASE_WEB_PROD }}
